### ISSUE TITLE
TypeError: get_calendar() got an unexpected keyword argument 'cache'

### ISSUE THREAD

**Issue by mikemsq** [ValueRaider/yfinance-cache#30]
exchange_calendars package doesn't support parameter 'cache' 

Error:
Traceback (most recent call last):
  File "/Users/mike/Projects/eiten/test_yfc.py", line 3, in <module>
    hist = msft.history(period="max")
  File "/Users/mike/Projects/eiten/venv/lib/python3.9/site-packages/yfinance_cache/yfc_ticker.py", line 178, in history
    sched = yfct.GetExchangeSchedule(exchange, d_now-(7*td_1d), d_now+td_1d)
  File "/Users/mike/Projects/eiten/venv/lib/python3.9/site-packages/yfinance_cache/yfc_time.py", line 180, in GetExchangeSchedule
    cal = GetCalendar(exchange)
  File "/Users/mike/Projects/eiten/venv/lib/python3.9/site-packages/yfinance_cache/yfc_time.py", line 126, in GetCalendar
    cal = xcal.get_calendar(cal_name, start=start, cache=True)
TypeError: get_calendar() got an unexpected keyword argument 'cache'

Sample code:
import yfinance_cache as yf
msft = yf.Ticker("MSFT")
hist = msft.history(period="max")
print(hist)

**Comment by ValueRaider** [comment]
I've pushed a fix.

I have a PR pending with `exchange_calendars` module to improve startup time. Until it's merged, the first ticker access in a script will be laggy.

**Comment by mikemsq** [comment]
Fixed!
Thanks a lot
