### ISSUE TITLE
cannot download (historical) currency data

### ISSUE THREAD

**Issue by biddisco** [ValueRaider/yfinance-cache#69]
This example example fails with an error
```
import pandas as pd
import yfinance as yf
import yfinance_cache as yfc
import datetime as dt

start_date = dt.datetime(2023,11,1)
end_date = dt.datetime.today()

EUR_USD = yfc.Ticker("EURUSD=X")
df_eur_usd = EUR_USD.history(start=start_date, end=end_date)
```
The full error is 
```
Traceback (most recent call last):
  File "/home/biddisco/src/grox/transactions/get-currencies.py", line 12, in <module>
    df_eur_usd = EUR_USD.history(start=start_date, end=end_date)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance_cache/yfc_ticker.py", line 230, in history
    h = hist.get(start_d, end_d, period=None, max_age=max_age, trigger_at_market_close=trigger_at_market_close, quiet=quiet)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance_cache/yfc_prices_manager.py", line 889, in get
    self._fetchAndAddRanges_contiguous(ranges_to_fetch, prepost, debug_yf, quiet=quiet)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance_cache/yfc_prices_manager.py", line 1067, in _fetchAndAddRanges_contiguous
    h2_pre = self._fetchYfHistory(r[0], r[1], prepost, debug)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance_cache/yfc_prices_manager.py", line 1764, in _fetchYfHistory
    df = self._fetchYfHistory_dateRange(fetch_start_pad, fetch_end, prepost, debug)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance_cache/yfc_prices_manager.py", line 2417, in _fetchYfHistory_dateRange
    raise e
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance_cache/yfc_prices_manager.py", line 2392, in _fetchYfHistory_dateRange
    df = self.dat.history(**history_args)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance/base.py", line 78, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance/scrapers/history.py", line 343, in history
    df = self._fix_zeroes(df, interval, tz_exchange, prepost)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance/utils.py", line 104, in wrapper
    result = func(*args, **kwargs)
  File "/home/biddisco/.local/lib/python3.10/site-packages/yfinance/scrapers/history.py", line 1074, in _fix_zeroes
    df2.loc[f_prices_bad.any(axis=1) & f_vol_zero_or_nan, "Volume"] = tag
ValueError: operands could not be broadcast together with shapes (183,) (184,) 
```
Any idea what's wrong?

**Comment by ValueRaider** [comment]
Traceback has clues. What version yfinance?

**Comment by biddisco** [comment]
Both installed with pip
```
yfinance==0.2.40
yfinance-cache==0.6.4
```
I just upgraded yfinance to 0.2.41 and that test runs ok now. I will experiment more. Thanks

**Comment by biddisco** [comment]
Seems fine now. Closing issue. Thanks again.
