### ISSUE TITLE
KeyError when getting data for stocks listed on the BSE (Bombay Stock Exchange) 

### ISSUE THREAD

**Issue by ishan-agarwal** [ValueRaider/yfinance-cache#71]
KeyError when getting data for stocks listed on the BSE (Bombay Stock Exchange) 

```
>>> stock = yf.Ticker("500182.BO")
>>> data = stock.history(period="1mo",interval="1d")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ishan/Desktop/etreco/venv/lib/python3.12/site-packages/yfinance_cache/yfc_ticker.py", line 94, in history
    yfct.SetExchangeTzName(exchange, tz_name)
  File "/home/ishan/Desktop/etreco/venv/lib/python3.12/site-packages/yfinance_cache/yfc_time.py", line 36, in SetExchangeTzName
    exchange_lock = yfcd.exchange_locks[exchange]
                    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'YHD'
```

**Comment by ValueRaider** [comment]
Ticker not real.

**Comment by vityav** [comment]
I get the same error with any of the major indexes (^DJI, ^GSPC, ^IXIC, etc) but they work in the base library. Would it be possible to add support for them?

**Comment by ValueRaider** [comment]
@vityav create a new issue, need to think about it. Core assumption is a symbol trades on a real exchange with real trading hours.

**Comment by ishan-agarwal** [comment]
The same ticker works on the base library. 

```
Python 3.12.5 (main, Aug 17 2024, 16:46:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yfinance as yf
>>> stock = yf.Ticker("500182.BO")
>>> data = stock.history(period="1mo",interval="1d")
>>> data
                                  Open         High          Low        Close  Volume  Dividends  Stock Splits  Capital Gains
Date
2024-08-12 00:00:00-04:00  5207.250000  5323.649902  5184.250000  5312.899902    6225        0.0           0.0            0.0
2024-08-13 00:00:00-04:00  5350.000000  5408.250000  5208.500000  5240.450195   27447        0.0           0.0            0.0
2024-08-14 00:00:00-04:00  5260.200195  5288.000000  4992.600098  5074.049805   67372        0.0           0.0            0.0
2024-08-16 00:00:00-04:00  5100.899902  5135.000000  5020.250000  5125.799805   27504        0.0           0.0            0.0
2024-08-19 00:00:00-04:00  5163.950195  5224.750000  5111.600098  5186.600098   11731        0.0           0.0            0.0
2024-08-20 00:00:00-04:00  5195.000000  5349.600098  5194.350098  5245.000000   24700        0.0           0.0            0.0
2024-08-21 00:00:00-04:00  5245.000000  5306.549805  5216.500000  5284.500000   16074        0.0           0.0            0.0
2024-08-22 00:00:00-04:00  5298.950195  5384.350098  5266.100098  5328.950195   51178        0.0           0.0            0.0
2024-08-23 00:00:00-04:00  5310.899902  5445.000000  5310.899902  5387.299805   15625        0.0           0.0            0.0
2024-08-26 00:00:00-04:00  5390.450195  5423.750000  5329.000000  5343.299805    9427        0.0           0.0            0.0
2024-08-27 00:00:00-04:00  5379.850098  5391.899902  5326.299805  5357.850098    5001        0.0           0.0            0.0
2024-08-28 00:00:00-04:00  5379.399902  5379.399902  5264.950195  5311.649902   15716        0.0           0.0            0.0
2024-08-29 00:00:00-04:00  5290.049805  5385.000000  5290.049805  5371.399902   14283        0.0           0.0            0.0
2024-08-30 00:00:00-04:00  5374.700195  5517.649902  5374.700195  5451.049805   51555        0.0           0.0            0.0
2024-09-03 00:00:00-04:00  5610.000000  5696.950195  5550.000000  5647.450195   19368        0.0           0.0            0.0
2024-09-04 00:00:00-04:00  5605.000000  5688.450195  5604.950195  5682.750000   22205        0.0           0.0            0.0
2024-09-05 00:00:00-04:00  5699.649902  5799.000000  5650.100098  5735.299805   13770        0.0           0.0            0.0
2024-09-06 00:00:00-04:00  5732.000000  5769.000000  5650.000000  5741.399902   16276        0.0           0.0            0.0
2024-09-09 00:00:00-04:00  5749.950195  5770.000000  5687.549805  5741.350098    9064        0.0           0.0            0.0
2024-09-10 00:00:00-04:00  5800.000000  5864.000000  5659.600098  5668.149902   16524        0.0           0.0            0.0
```

**Comment by ValueRaider** [comment]
But `500182.BO` doesn't appear in search results on Yahoo Finance, usually a good reason for that.
