### ISSUE TITLE
CCC Exchange missing for Crypto, how to add?

### ISSUE THREAD

**Issue by sonique6784** [ValueRaider/yfinance-cache#78]
OS: Linux
Version: python 3.12
yfinance_cache: 0.7.x

Ticker requested: ADA-USD
Exchange: CCC

according to the exception below, a timezone need to be provided (I assume to establish when is the day-close)

```
Traceback (most recent call last):
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_ticker.py", line 105, in history
    yfct.SetExchangeTzName(exchange, tz_name)
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_time.py", line 37, in SetExchangeTzName
    raise Exception(f"Need to add mapping of exchange {exchange} to xcal")
Exception: Need to add mapping of exchange CCC to xcal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_multi.py", line 158, in download_one_parallel
    df = download_one(ticker, start=start, end=end, max_age=max_age,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_multi.py", line 177, in download_one
    df = dat.history(
         ^^^^^^^^^^^^
  File "/momentum/lib/python3.12/site-packages/yfinance_cache/yfc_ticker.py", line 108, in history
    raise Exception(f"Need to add mapping of exchange {exchange} to xcal (ticker={self._ticker})")
Exception: Need to add mapping of exchange CCC to xcal (ticker=ADA-USD)
```

I tried to add the following line in `yfc_dat.py` line 157
```
# Crypto        
exchangeToXcalExchange["CCC"] = "IEPA"  # ICE Data Services
```

it seems to improve things

**Comment by ValueRaider** [comment]
That 1 line is the fix - do you want to submit pull request for the credit?

**Comment by ValueRaider** [comment]
Actually `24/7` is the better fix, `IEPA` was treated as closed during Jimmy Carter federal holiday.

**Comment by sonique6784** [comment]
I tried `24/7`, but got another error:

```
Traceback (most recent call last):
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_multi.py", line 158, in download_one_parallel
    df = download_one(ticker, start=start, end=end, max_age=max_age,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_multi.py", line 177, in download_one
    df = dat.history(
         ^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_ticker.py", line 246, in history
    h = hist.get(start_d, end_d, period=None, max_age=max_age, trigger_at_market_close=trigger_at_market_close, quiet=quiet)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_prices_manager.py", line 714, in get
    h = self._fetchYfHistory(start, tomorrow, prepost, debug_yf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_prices_manager.py", line 2063, in _fetchYfHistory
    intervals_missing_df = yfct.IdentifyMissingIntervals(self.exchange, start, end, self.interval, received_interval_starts, ignore_breaks=True)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_time.py", line 1862, in IdentifyMissingIntervals
    intervals = GetExchangeScheduleIntervals(exchange, interval, start, end, week7days=week7days, ignore_breaks=ignore_breaks, exclude_future=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/yfinance_cache/yfc_time.py", line 728, in GetExchangeScheduleIntervals
    s = GetExchangeSchedule(exchange, start_d, end_d)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/momentum/lib/python3.12/site-packages/yfinance_cache/yfc_time.py", line 298, in GetExchangeSchedule
    s = cal.schedule.loc[str(start_d.year):str(end_d_sub1.year)].copy()
        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/pandas/core/indexing.py", line 1411, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/pandas/core/indexing.py", line 1443, in _get_slice_axis
    indexer = labels.slice_indexer(slice_obj.start, slice_obj.stop, slice_obj.step)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/pandas/core/indexes/datetimes.py", line 697, in slice_indexer
    raise KeyError(
KeyError: 'Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is not allowed.'

```

**Comment by ValueRaider** [comment]
I haven't seen your specific error before, but I have just sent out a release that fixes other various related bugs, hopefully that fixes. If not, submit a new bug report.

**Comment by sonique6784** [comment]
@ValueRaider , I still face the issue. here is a snippet of code to reproduce the issue:
* it works well if I remove ETH-USD
* it fails with all crypto assets I tested (BTC, ADA, ETH, SOL...)

```python
import yfinance_cache as yf
import pandas_ta as ta
from datetime import datetime
import dateutil.relativedelta
from datetime import date, timedelta

asset_list_joined="SPY ETH-USD"
dateformat="%Y-%m-%d"

now = datetime.now()
start_date = (now - dateutil.relativedelta.relativedelta(weeks=7*4)).strftime(dateformat)
end_date=now.strftime(dateformat)
interval="1d"

yf.download(asset_list_joined, start=start_date, end=end_date, interval=interval)["Close"]
```

**Comment by ValueRaider** [comment]
I can reproduce error now, I'll fix soon.

**Comment by ValueRaider** [comment]
To test if my hunch is correct, can you run this (adapt as needed):
> rm -r ~/.cache/py-yfinance-cache/exchange-CCC

This should have happened automatically once when you upgraded to 0.7.2. Use YFC for a while to be sure error doesn't come back.

**Comment by sonique6784** [comment]
Hi @ValueRaider thanks for looking into this. 
I removed the CCC cache, but I still got the same error.
I removed the entire cache `rm -rf ~/.cache` and still got the same error.

**Comment by ValueRaider** [comment]
Double-check you have version 0.7.2:
> ls -d ~/.local/lib/python3.12/site-packages/yfinance_cache*dist-info

If that shows 0.7.2, then try updating to 0.7.3, I fixed another bug affecting 24-hour exchanges.

**Comment by crypdick** [comment]
I still see this error on 40ae6d3

**Comment by ValueRaider** [comment]
@crypdick What's your traceback?

**Comment by crypdick** [comment]
sorry for the delay:

```shell
Traceback (most recent call last):
  File ".../repro_yfinance_cache_btc_bug.py", line 31, in <module>
    main()
  File ".../repro_yfinance_cache_btc_bug.py", line 27, in main
    ticker.history(start=start, end=now, interval="1h")
  File ".venv/lib/python3.12/site-packages/yfinance_cache/yfc_ticker.py", line 207, in history
    sched_14d = yfct.GetExchangeSchedule(exchange, start_dt.date(), start_dt.date()+14*td_1d)
  File ".venv/lib/python3.12/site-packages/yfinance_cache/yfc_time.py", line 297, in GetExchangeSchedule
    s = cal.schedule.loc[str(start_d.year):str(end_d_sub1.year)].copy()
  File ".venv/lib/python3.12/site-packages/pandas/core/indexing.py", line 1191, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File ".venv/lib/python3.12/site-packages/pandas/core/indexing.py", line 1411, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File ".venv/lib/python3.12/site-packages/pandas/core/indexing.py", line 1443, in _get_slice_axis
    indexer = labels.slice_indexer(slice_obj.start, slice_obj.stop, slice_obj.step)
  File ".venv/lib/python3.12/site-packages/pandas/core/indexes/datetimes.py", line 697, in slice_indexer
    raise KeyError(
KeyError: 'Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is not allowed.'
```

repro:

```python
#!/usr/bin/env python3
import datetime
import requests

import yfinance_cache as yfc


def main() -> None:
    session = requests.Session()
    session.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
        )
    })
    now = datetime.datetime.now(datetime.timezone.utc)
    start = now - datetime.timedelta(days=1)
    ticker = yfc.Ticker("BTC-USD", session=session)
    ticker.history(start=start, end=now, interval="1h")


if __name__ == "__main__":
    main()
```

ran it with with uv run
Python 3.12.10
yfinance-cache commit 40ae6d3
yfinance 0.2.54, pandas 2.2.3
Linux 6.14.0-29-generic

**Comment by crypdick** [comment]
@valueraider can you email me at public@ricardodecal.com

**Comment by ValueRaider** [comment]
My email is ValueRaider@protonmail.com

**Comment by ValueRaider** [comment]
When I run YFC on your cache I immediately get this:
```
python ./debug-crypto.py 
YFC recalculating 'Final?' column in prices, estimate 2.3 minutes to process 1593 tickers.
```

This tells me you are running an old version of YFC, despite what PIP etc is reporting. So upgrade.
